#!/bin/bash
set -x
created_tmp=0
if [ ! -e tmp ]; then
    mkdir tmp
    created_tmp=1
    echo "Creating tmp"
else
    rm -rf tmp/MCTF
fi
svn export src tmp/MCTF
tar --create --file=tmp/MCTF.tar -C tmp MCTF
gzip -9 tmp/MCTF.tar
mv tmp/MCTF.tar.gz .
if [ $created_tmp = 1 ]; then
    rm -rf tmp
    echo "Deleting tmp"
fi
