nohup ./slopesTRL_1.sh &
nohup ./slopesTRL_2.sh &
nohup ./slopesTRL_3.sh &
nohup ./slopesTRL_4.sh &
nohup ./slopesTRL_5.sh &
nohup ./slopesTRL_6.sh &
nohup ./slopesTRL_7.sh &
nohup ./slopesTRL_8.sh &
nohup ./slopesTRL_9.sh &
nohup ./slopesTRL_10.sh &
nohup ./slopesTRL_11.sh &
nohup ./slopesTRL_12.sh &
nohup ./slopesTRL_13.sh &
nohup ./slopesTRL_14.sh &
nohup ./slopesTRL_15.sh &
nohup ./slopesTRL_16.sh &
nohup ./slopesTRL_17.sh &
nohup ./slopesTRL_18.sh &
nohup ./slopesTRL_19.sh &
nohup ./slopesTRL_20.sh &
top
